project_name: harific
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./harific.go
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: pb33f
      name: homebrew-taps
      token: "{{ .Env.GITHUB_TOKEN }}"

    commit_author:
      name: goreleaserbot
      email: goreleaser@pb33f.io

    homepage: "https://pb33f.io/harific"
    description: "Lightning-fast HAR file viewer and analysis tool with TUI and mock server"

    install: |
      bin.install "harific"

snapshot:
  name_template: "{{ .Tag }}"

# Docker images are built separately in GitHub Actions (publish.yaml)
# to support multi-platform builds with proper manifest lists
# dockers:
#   - image_templates:
#       - "docker.io/pb33f/harific:{{ .Tag }}"
#       - "docker.io/pb33f/harific:latest"
#       - "ghcr.io/pb33f/harific:{{ .Tag }}"
#       - "ghcr.io/pb33f/harific:latest"
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--platform=linux/arm64"

upx:
  -
    enabled: true
    goos: [ linux , darwin ]
    goarch: [ arm, amd64 ]
    goarm: [ 8 ]
    goamd64: [ v1 ]
    compress: best
    lzma: true
    brute: true
